// apps/docs/components/not251/Chord.tsx
"use client";
import { chord as generateChord, positionVector } from "@not251/not251";
import { useState, useEffect } from "react";
import { usePlaygroundContext } from "./PlaygroundContext"; // Import context hook

function generateChordNotes(
  scala: positionVector,
  grado: number,
  octave: number,
  position: number,
  preVoices: number,
  postVoices: number,
  isInvert: boolean,
  isNegative: boolean,
  standardNegative: boolean,
  negativePos: number
) {
  const chordNotes: positionVector = generateChord({
    scala: scala, // Use scala from context
    octave: octave,
    grado: grado,
    position: position,
    preVoices: preVoices,
    postVoices: postVoices,
    isInvert: isInvert,
    isNegative: isNegative,
    standardNegative: standardNegative,
    negativePos: negativePos,
  });
  return chordNotes;
}

export default function Chord() {
  const { setNotes, scala } = usePlaygroundContext(); // Get scala from context

  // State for chord parameters
  const [octave, setOctave] = useState<number>(2);
  const [grado, setGrado] = useState<number>(0);
  const [position, setPosition] = useState<number>(0);
  const [preVoices, setPreVoices] = useState<number>(3);
  const [postVoices, setPostVoices] = useState<number>(3);
  const [isInvert, setIsInvert] = useState<boolean>(false);
  const [isNegative, setIsNegative] = useState<boolean>(false);
  const [standardNegative, setStandardNegative] = useState<boolean>(false);
  const [negativePos, setNegativePos] = useState<number>(0);

  // State for the generated chord notes
  const [chordNotes, setChordNotes] = useState<positionVector>(
    generateChordNotes(
      scala,
      grado,
      octave,
      position,
      preVoices,
      postVoices,
      isInvert,
      isNegative,
      standardNegative,
      negativePos
    )
  );

  // Update the context and regenerate chord notes when parameters change
  useEffect(() => {
    const newChordNotes = generateChordNotes(
      scala,
      grado,
      octave,
      position,
      preVoices,
      postVoices,
      isInvert,
      isNegative,
      standardNegative,
      negativePos
    );
    setChordNotes(newChordNotes);
    setNotes(newChordNotes); // Update context
  }, [
    scala,
    grado,
    octave,
    position,
    preVoices,
    postVoices,
    isInvert,
    isNegative,
    standardNegative,
    negativePos,
    setNotes,
  ]);

  return (
    <div className="flex flex-col items-start space-y-4 border border-white p-4 rounded-lg">
      <h2 className="text-2xl">Chord</h2>

      {/* Octave Slider */}
      <div className="flex items-center space-x-2">
        <label>Octave:</label>
        <input
          type="range"
          min={1}
          max={3}
          step={1}
          value={octave}
          onChange={(e) => setOctave(Number(e.target.value))}
          className="w-32"
        />
        <span>{octave - 1}</span>
      </div>

      {/* Octave Slider */}
      <div className="flex items-center space-x-2">
        <label>Grado:</label>
        <input
          type="range"
          min={0}
          max={7}
          step={1}
          value={grado}
          onChange={(e) => setGrado(Number(e.target.value))}
          className="w-32"
        />
        <span>{grado + 1}</span>
      </div>

      {/* Position Slider */}
      <div className="flex items-center space-x-2">
        <label>Position:</label>
        <input
          type="range"
          min={0}
          max={7}
          value={position}
          onChange={(e) => setPosition(Number(e.target.value))}
          className="w-32"
        />
        <span>{position}</span>
      </div>

      {/* Pre Voices Slider */}
      <div className="flex items-center space-x-2">
        <label>Pre Voices:</label>
        <input
          type="range"
          min={0}
          max={7}
          step={1}
          value={preVoices}
          onChange={(e) => setPreVoices(Number(e.target.value))}
          className="w-32"
        />
        <span>{preVoices}</span>
      </div>

      {/* Post Voices Slider */}
      <div className="flex items-center space-x-2">
        <label>Post Voices:</label>
        <input
          type="range"
          min={0}
          max={7}
          step={1}
          value={postVoices}
          onChange={(e) => setPostVoices(Number(e.target.value))}
          className="w-32"
        />
        <span>{postVoices}</span>
      </div>

      {/* Invert Checkbox */}
      <div className="flex items-center space-x-2">
        <label>Invert:</label>
        <input
          type="checkbox"
          checked={isInvert}
          onChange={(e) => setIsInvert(e.target.checked)}
        />
      </div>

      {/* Negative Checkbox */}
      <div className="flex items-center space-x-2">
        <label>Negative:</label>
        <input
          type="checkbox"
          checked={isNegative}
          onChange={(e) => setIsNegative(e.target.checked)}
        />
      </div>

      {/* Standard Negative Checkbox */}
      <div className="flex items-center space-x-2">
        <label>Standard Negative:</label>
        <input
          type="checkbox"
          checked={standardNegative}
          onChange={(e) => setStandardNegative(e.target.checked)}
        />
      </div>

      {/* Negative Position Slider */}
      <div className="flex items-center space-x-2">
        <label>Negative Position:</label>
        <input
          type="range"
          min={0}
          max={11}
          step={1}
          value={negativePos}
          onChange={(e) => setNegativePos(Number(e.target.value))}
          className="w-32"
        />
        <span>{negativePos}</span>
      </div>
    </div>
  );
}

// apps/web/src/lib/components/not251/Chord.svelte
<script lang="ts">
	import {
		chord as generateChord,
		intervalVector,
		getChordName,
		positionVector
	} from '@not251/not251';
	import { Slider } from '$lib/components/ui/slider';
	import * as Card from '$lib/components/ui/card';
	import { Label } from '$lib/components/ui/label';
	import { Switch } from '$lib/components/ui/switch';
	import { chord, scale } from './store';
	import { initChordOptions } from './utils';

	let options = $state(initChordOptions);

	let chordNotes = $derived(
		generateChord({
			root: $scale.options.root[0],
			grado: options.grado[0],
			isInvert: options.isInvert,
			isNegative: options.isNegative,
			standardNegative: options.standardNegative,
			negativePos: options.negativePos[0],
			preVoices: options.preVoices[0],
			position: options.position[0],
			postVoices: options.postVoices[0],
			octave: options.octave[0] + 2,
			scala: $scale.notes,
			selection: new intervalVector([2], 12, 0)
		})
	);

	$effect(() => {
		$chord = {
			options: {
				scale: options.scale,
				grado: options.grado,
				octave: options.octave,
				preVoices: options.preVoices,
				position: options.position,
				postVoices: options.postVoices,
				isInvert: options.isInvert,
				isNegative: options.isNegative,
				standardNegative: options.standardNegative,
				negativePos: options.negativePos
			},
			notes: chordNotes
		};
	});
</script>

<Card.Root class="w-full max-w-prose">
	<Card.Header>
		<Card.Title class="text-2xl">Chord</Card.Title>
		<Card.Description>Chord generation</Card.Description>
	</Card.Header>
	<Card.Content>
		<div class="flex flex-col gap-5">
			<div class="space-y-2">
				<Label for="preVoices">Pre-Voices: {options.preVoices}</Label>
				<Slider id="preVoices" bind:value={options.preVoices} min={1} max={7} step={1} />
			</div>
			<div class="space-y-2">
				<Label for="grado">Grado: {options.grado}</Label>
				<Slider id="grado" bind:value={options.grado} min={0} max={7} step={1} />
			</div>
			<div class="space-y-2">
				<Label for="position">Position: {options.position}</Label>
				<Slider id="position" bind:value={options.position} min={0} max={7} step={1} />
			</div>
			<div class="space-y-2">
				<Label for="postVoices">Post-Voices: {options.postVoices}</Label>
				<Slider id="postVoices" bind:value={options.postVoices} min={1} max={7} step={1} />
			</div>
			<div class="space-y-2">
				<Label for="octave">Octave: {options.octave}</Label>
				<Slider id="octave" bind:value={options.octave} min={-2} max={8} step={1} />
			</div>

			<!-- SWITCHES -->
			<div class="flex flex-col gap-2">
				<div class="flex items-center space-x-2">
					<Switch id="isInvert" bind:checked={options.isInvert} />
					<Label for="isInvert">Invert</Label>
				</div>

				<div class="flex items-center space-x-2">
					<Switch id="isNegative" bind:checked={options.isNegative} />
					<Label for="isNegative">Negative</Label>
				</div>

				<div class="flex items-center space-x-2">
					<Switch id="standardNegative" bind:checked={options.standardNegative} />
					<Label for="standardNegative">Standard Negative</Label>
				</div>
			</div>
			<div class="space-y-2">
				<Label for="negativePos">Negative Position: {options.negativePos}</Label>
				<Slider id="negativePos" bind:value={options.negativePos} min={0} max={11} step={1} />
			</div>
		</div>
	</Card.Content>
	<Card.Footer class="flex w-full items-center justify-center gap-2">
		<p></p>
	</Card.Footer>
</Card.Root>
